### PR TITLE
Adding tutorial for academic certificates on ethereum

### PR DESCRIPTION
**Pull request by nanspro**
Contains detailed explanation for 

- [x] Deploying and connecting to the node
- [x] Writing and compiling a DApp
- [x] Interacting with the smart contract

Related to  #19

### CODE REVIEW

**Comment by nanspro** [comment]
@easeev  please review, I have added the docs at appropriate position in chainstack documentation.

**Comment by zaidmo123** [comment]
Hi Rahul

After some issues with getting the truffle-hdwallet-provider installed which I resolved (in issue log), I've managed to get to this step:

```
For development and testing purposes let's deploy these contracts to local ganache network!

Run truffle dev to get inside truffle's console running with ganache locally on "localhost:9545" and then deploy using migrate in the console. You'll see contract's address and gas used, the account from which they were deployed etc.
```
At this stage I have tried **truffle dev** and **truffle dev localhost:9545** which launches the console


`
Note: If you are deploying to mainnet you'll have to use real ether, Run truffle migrate --network mainnet to successfully deploy contracts through chainstack node.
`
Do I need to migrate to development?
I tried **truffle migrate --compile-all --reset --network development**

I get the error:

> Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 9545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network

Interacting with contracts
```
You can interact with your contract through the console or write truffle tests. In your console enter test to run truffle tests(which interacts and checks if the contract functions are working or not).

Have a look at test/test.js to see how they are written.
```
Please can you give more info on this test.js comment. My test folder was empty.

```
Truffle Console

You can also interact with deployed contracts by running commands into console. Before that you should have a truffle developer console running, with migrated contracts.

Creating Instance
let instance = DocStamp.deployed()
```
At this point I get an **undefined** error

`instance
`
I receive the error:
truffle(develop)> instance
Thrown:
Error: DocStamp has not been deployed to detected network (network/artifact mismatch)


```
let accounts = await web3.eth.getAccounts()
Interacting with instance
let owner = await instance.owningAuthority()
let result = await instance.issueCertificate("rahul", "developer", {from: owner)

// will fail if called by someone else 
let result = await instance.issueCertificate("name", "details", {from: accounts[1]})

let verified = await instance.verifyCertificate("name", "details", "0x3893c7e8b4091794fa54e4b22cc506042f2b00e07d965aa3927aff7f12163955", {from: owner})
verified
Note: To interact with the contracts deployed on chainstack node you'll just have to create the web3 provider with rpc url of node like this const web3 = new Web3(rpcURL)

```
Can you please add more comments explaining what is happening with these steps, and clarify what and where to enter: **create the web3 provider with rpc url of node like this const web3 = new Web3(rpcURL)**

**Comment by zaidmo123** [comment]
Also noticed that the Ownable smart contract is not being deployed.

Perhaps deploy_contract.js should have:

```
var Ownable = artifacts.require("./Ownable.sol");
var DocStamp = artifacts.require("./DocStamp.sol");

module.exports = function(deployer) {
deployer.deploy(Ownable);
deployer.deploy(DocStamp);
};
```

**Comment by nanspro** [comment]
@zaidmo123  sorry i was busy with something else!!
I have updated the docs and i hope that will answer all your queries but i'll mention them here too.

> Also noticed that the Ownable smart contract is not being deployed.

DocStamp inherits from Ownable so when it is deployed it inherits ownable's methods before.


> For development and testing purposes let's deploy these contracts to local ganache network!

An mistake, no need for ganache anywhere use truffle's local development.

> At this stage I have tried **truffle dev** and **truffle dev localhost:9545** which launches the console
> Do I need to migrate to development?

Yes, after running `truffle dev` run `migrate` in that console.

> Where does ganache fit in? Do I need to install it, and migrate to it?

No

> > Could not connect to your Ethereum client with the following parameters:
> > - host       > 127.0.0.1
> > - port       > 9545
> > - network_id > 5777
> > Please check that your Ethereum client:
> > - is running
> > - is accepting RPC connections (i.e., "--rpc" option is used in geth)
> > - is accessible over the network

This error won't come if you are running truffle development environment somewhere using truffle dev

> At this point I get an **undefined** error. Is this the right type of syntax to enter into truffle console?

It is not an error, just type instance after that and you will see the contract object.

**Comment by zaidmo123** [comment]
Thanks Rahul,

Still struggling to get this working.

**truffle > migrate** only deploys the 1_initial_migration.js file. Not deploy_contract.js
image

With this error:
image

If I rename deploy_contract.js to 2_deploy_contract.js, then all contracts are deployed
image

Now, with the contracts deployed. on truffle console I try to submit the entries you provided.

image

image

But I'm getting these errors:
image

**Comment by nanspro** [comment]
@zaidmo123  ahh looks like i have made some typos!! 
try `let result = await instance.issueCertificate("rahul", "developer", {from: owner})`

**Comment by nanspro** [comment]
I will update it after you get it running once, tell me if you face any other issue :smile:

**Comment by zaidmo123** [comment]
Thanks Rahul,
It's working now:
image

image

A question:
The certificate number, 0x3893c7e8b4091794fa54e4b22cc506042f2b00e07d965aa3927aff7f12163955 - is there any way I can lookup this certificate number after issuing it, from truffle console?
I typed result but it's not listed anywhere in this transaction receipt.
image
w

**Comment by nanspro** [comment]
enter `result['logs']` to see events emitted(certificate will be there)
@zaidmo123  explained this in the doc also and removed ganache part

**Comment by zaidmo123** [comment]
> enter `result['logs']` to see events emitted(certificate will be there)
> @zaidmo123 explained this in the doc also and removed ganache part

Rahul, can you please confirm this update (can't see the changes on the tutorial)

**Comment by nanspro** [comment]
https://github.com/chainstack/docs/blob/c5f9433145538e3fd79125ae398436d58fe2eede/docs/tutorials/certificates.md
See *Interacting with Instance*

**Comment by nanspro** [comment]
@zaidmo123  ?

**Pull request merged**
