### PR TITLE
Add copy to clipboard

### LINKED ISSUE #50: Add copy to clipboard
Implement a copy to clipboard feature for vuepress

### PR DESCRIPTION
**Pull request by akegaviar**
Closes #50

I checked on my end in Opera & Chrome and it works. Please maybe check in Windows too?

### CODE REVIEW

**Review by neewy — COMMENTED** [review]
Does not work for me:
https://user-images.githubusercontent.com/11841667/112445525-46416600-8d60-11eb-92dc-c107e1d7599b.mov

**Comment by akegaviar** [comment]
@neewy 

- Changes merged to `master` are on `docs.dev.chainstack.com`.
- Changes merged to `prod` are on `docs.chainstack.com`.
- Changes **not** merged can only be viewed on your local instance.

To view changes locally:
1. Clone `git clone git@github.com:chainstack/docs.git`
2. Checkout the branch `git checkout copy-to-clipboard`
3. Install dependencies `npm install`
4. Run the local instance with the changes from the branch you have checked out `npm run  dev`
5. In your browser, open `http://localhost:8080/`

**Comment by neewy** [comment]
@akegaviar thank you! Will look at it

**Review by easeev — APPROVED** [review]
LGTM

**Review by CaJIbHuK — APPROVED** [review]

**Comment by CaJIbHuK** [comment]
works for me
image

**Pull request merged**
