### PR TITLE
improve support plans article

### PR DESCRIPTION
**Pull request by ginstagram**
## Description
Edit link to the pricing page and rephrase the Downgrade option column according to the suggestions

### CODE REVIEW

**Comment by akegaviar** [comment]
@denis-at-chainstack I'm thinking maybe we don't need the **Downgrade option** column at all. What do you think?

**Comment by denis-at-chainstack** [comment]
@akegaviar actually that's what I proposed to do :)

**Review by conor2e — APPROVED** [review]
LGTM

**Comment by akegaviar** [comment]
@denis-at-chainstack are you okay with the changes?

**Pull request merged**
