### PR TITLE
Add mandatory --sequence flag to checkcommitreadiness

### PR DESCRIPTION
**Pull request by neewy**
While following the docs I wondered why we use `data` while telling user to use `MOUNT_DIRECTORY` in docker mount path

### CODE REVIEW

**Comment by neewy** [comment]
Also, fabric tools binary now requires sequence parameter:

```
/MOUNT_DIRECTORY # peer lifecycle chaincode checkcommitreadiness -o $ORDERER_ADDRESS --
channelID defaultchannel --tls --cafile $ORDERER_CA --name fabcar --version 1.0.0 --ini
t-required
Error: The required parameter 'sequence' is empty. Rerun the command with --sequence flag
```

**Comment by akegaviar** [comment]
> While following the docs I wondered why we use data while telling user to use MOUNT_DIRECTORY in docker mount path

We use `MOUNT_DIRECTORY` as a variable that has an explanation `MOUNT_DIRECTORY — the name of the directory that you mounted at the previous step.`

We use `data` as an example (also used as a mount point example in the previous step). We aren't going to use a variable in an example.

**Comment by neewy** [comment]
@akegaviar sounds good, rebased the commit. Let's check the sequence parameter later

**Review by akegaviar — APPROVED** [review]
Good catch!

**Pull request merged**
